### PR TITLE
Added error emitter

### PR DESCRIPTION
**Pull request by basvdijk**
With this error emitter it is possible to catch errors with the serial port and show it to the user.

### CODE REVIEW

**Comment by bigkevmcd** [comment]
I guess it makes sense to drop the console.logging of the error, and just emit the message?

I don't think I've actually ever seen an error in normal use

**Comment by basvdijk** [comment]
The situation where I needed an error event was when I used the port of another device instead of the RFXcom.

**Comment by iangregory** [comment]
Another scenario is where the node.js application doesn't have permissions to open the serial port.

**Comment by bigkevmcd** [comment]
So, does it seem reasonable to drop the logging, and just emit the message, rather than duplicating the logic?

**Comment by iangregory** [comment]
I'd wrap the logging in a check of self.options.debug in the same way as it is in the "end" event handler.

**Comment by bigkevmcd** [comment]
Seems reasonable, @basvdijk can you take care of that in this branch, or if not, I'm happy to implement that.

**Comment by basvdijk** [comment]
@bigkevmcd By all means go ahead :)

**Comment by maxwellhadley** [comment]
From version 0.8.0 up, the "error" serialport event is used as part of the dynamic disconnection/reconnection mechanism, making this PR redundant, as far as I can see.

**Pull request closed without merging**
