### PR TITLE
Added support for Blinds1 devices.

### PR DESCRIPTION
**Pull request by Digicrat**
I added support for Rollertrol blinds.  In theory this should also work for all other Blinds1 devices, though only the T0/Rollertrol configuration has been tested.

I haven't written a formal test for the test directory, but that should be easy for someone else to cook up (it might be a while before I'd have a chance to do so myself as I've got other priorities).

### CODE REVIEW

**Comment by maxwellhadley** [comment]
Thanks, I'll take a look at this when I get spare hour or two :)

**Comment by Digicrat** [comment]
Sure.  Thanks for a RFXCOM library that actually works (both the Perl and Python equivalent libraries seem to be incomplete dead projects). 

I just realized a usage example for the Rollertrol devices might be useful, so:

```
var rollertrol = new rfxcom.Blinds1(rfxtrx, rfxcom.blinds1.T0_ROLLERTROL);
rollertrol.close(['0x12','0x34','0x1']); // same syntax for open(), stop(), confirm() and set() functions.

```

IDs can also be specified as a single '/' delimited string.  Certain Blinds0 devices (not Rollertrol) may require a third ID byte as the first argument which is otherwise assumed to be 0.  The last ID argument is unit, which corresponds to the channel on Rollertrol remotes, with the value 0 reserved for 'All.'

**Comment by maxwellhadley** [comment]
Finally got a few hours spare!

I see you aren't actually using the subtype argument to the constructor, effectively you always end up with a BLINDS_T0 (i.e. Rollertrol) transmitter. I've defined subtypes BLINDS_T0 to BLINDS_T10 in lib/index.js - would it be OK to make the subtype mandatory, and use the existing definitions? Then I can extend support to the other blinds types as well.

You also seem to be using the deviceID argument differently from the other transmitters, if I follow your example correctly. To match the others, I would expect an argument which was either a string, or an array of strings, where the strings are the id and unit code, i.e.
`rollertrol.close("0x1234/1")`
     or
`rolertrol.close(["0x1234", "1"])` 
and not split into bytes. I'd prefer to make the interface uniform with the other transmitters.

Are these changes OK?

**Comment by Digicrat** [comment]
It's been a while since I looked at this ... but in general I'm always for consistency.

In terms of the constructor, I believe the subtype was ignored because I didn't need seem to need it, and it didn't seem necessary for anything other than error checking of the device ID format.  Making that a required argument is probably the better long-term implementation though, so go for it.

As for the deviceID format, I wrote the deviceId formatting in a way that worked most conveniently with the Rollertrol's format (which was a bit different from other protocols I looked at).  The code as written will accept either the array or string formats;

> 	rollertrol.close(['0x12','0x34','0x1']); // my preferred format
> 	rollertrol.close(['0','0x12','0x34','0x1'])
> 	rollertrol.close('0x12/0x34/1');
> 	rollertrol.close('0/0x12/0x34/1');
> 

If you want greater, consistency, we can add a condition to accept your preferred form, ie::

> 	rollertrol.close(["0x001234","1");


with:
```
} else if (parts.length == 2) {
	var val = parseInt(parts[0]);
	return {
		byte0: (val & 0xFF0000) >> 8,
		byte1: (val & 0xFF00) >> 8,
		byte0: val & 0xFF,
		unitCode: parseInt(parts[1])
	};
}
```

Note: Re-reading my code, the parseInt() calls should probably omit the radix argument (16), and let the prefix automatically determine if it's decimal or hex.

**Comment by maxwellhadley** [comment]
I see where you are coming from - you have already gone to the trouble of creating the array of bytes in your application and just want to pass them to the RFXtrx. However, I'm trying to extend support to all the Blinds1 devices, not just BLINDS_T0. That means coping with types like the Raex & ASP which don't have a unit code at all, and the oddball DC106, Forest & Sunpery where part of the unit ID is squeezed into the high nibble of the unit code byte. Would you expect to have to supply pre-canned byte sequences for those, combining unit ID & unit code?

My general principle is to handle all the subtype-specific differences within this package, hiding the gory details as much as possible, and checking the supplied addresses etc., are within allowed limits, and the command supported, appropriately for each subtype. Similarly, the device data received events always 'decode' the address into a consistent format (you can always use the low-level `receive` event to get the raw bytes if you want them).

It would be possible to accept a byte Array as an alternative DeviceID format, either by checking for length > 2, or preferably by checking for an Array of Numbers, rather than Strings. But then on the Principle of Least Astonishment, I would have to implement this alternative for all the other transmitter types as well (which rules out the length > 2 check). Not keen.

Would it be too much to ask you to change the deviceID format you use in your application to be consistent with everything else? I'll push my work in progress on this merge to `rfxcom/node-rfxcom:add-blinds1` in a while, so you can have a look at it. I'll hold off starting on the tests until you get back.

Thanks!

**Comment by maxwellhadley** [comment]
I've pushed my modified version now!

**Comment by bigkevmcd** [comment]
For some background, the "string" format evolved from simplifying configuration file entries.

**Comment by maxwellhadley** [comment]
OK. The "array of strings" format came from my node-red-contrib-rfxcom package where I am already picking apart MQTT-style /-separated strings anyway

**Comment by maxwellhadley** [comment]
Just pushed unit tests...

**Comment by maxwellhadley** [comment]
Pushed new version blinds1 receive event (with unit tests) - and with added BLINDS_T13 subtype

**Comment by maxwellhadley** [comment]
@digicrat - I'd like to add a couple more commands, namely Set Lower Limit and Reverse Direction. The new functions are setLowerLimit() and reverse(). That means it would be better if the existing set() function was renamed to setLimit(). Is this OK with you?

**Comment by maxwellhadley** [comment]
Now merged and published to npm as 0.13.0

**Pull request merged**
