### PR TITLE
Oregon rain sensor

### PR DESCRIPTION
**Pull request by kalemena**
Hi,
Just minor changes to support Rain sensor from Oregon: PCR800.
Regards,

### CODE REVIEW

**Comment by bigkevmcd** [comment]
I won't accept patches without changes to the tests, can you please add some tests for this?

**Comment by kalemena** [comment]
Well, if I knew how to run the current tests, and then how to modify them, I would be glad to.
I'm not really a nodejs person :-( but appreciate you shared this lib.

**Comment by bigkevmcd** [comment]
Try running npm test then have a look at the existing tests for the handlers in test/rfxcom.spec.js

**Comment by maxwellhadley** [comment]
My long-outstanding PR https://github.com/bigkevmcd/node-rfxcom/pull/31 includes among other things support for rain sensors type 1 - 6 (and tests). Please can we make an effort to merge everything in together? It's been a long time!

**Comment by kalemena** [comment]
Looks like huge change to bring plenty features.
+1 to merge PR #31 if possible.

**Comment by bigkevmcd** [comment]
@maxwellhadley It's hard to accept a 5354 line diff to a project with only 2400 lines, if you break it up into separate parts, I would be willing to accept it piece by piece.

**Comment by maxwellhadley** [comment]
OK I'll break it up then. It will have to be a fairly manual process: I suggest I divide it up into 1) refactoring; 2) miscellaneous bug fixes; 3) revised serial port handling (I eliminated that elusive unknown message type issue!); 4) additional lighting types; 5) additional sensors; 6) energy meters. If that's OK?
You probably won't want to npm publish all the intermediate steps - is it possible to create a new branch for me to PR against, and then you can do one final merge at the end? I don't know enough about git(hub) to know if this is either possible or desirable.

**Comment by maxwellhadley** [comment]
Newly-published version 0.10.0 should handle Oregon PCR800 rainfall sensor (as RAIN2) now. Please can you test it, as I don't (yet) have one here. I'm closing this PR, so if there are problems, can you raise a new issue, please?

**Comment by kalemena** [comment]
Good for me regarding Oregon rain sensor.
Thanks for the support!

**Pull request closed without merging**
