### PR TITLE
Somfy RFY protocol

### PR DESCRIPTION
**Pull request by gizimoto**
Added basic support for the Somfy RTS blinds protocol (RFY protocol).  Specification based on existing projects on GitHub (i.e. not from RfxCom API documentation).

Includes new status handling of the 'list remotes' command including new 'list' event.

Only the rfxtrx433E unit supports the RFY protocol.

Solves #34

### CODE REVIEW

**Comment by bigkevmcd** [comment]
Can you add tests for this?

**Comment by alex198710** [comment]
Hello,
When do you plan to merge this PR ? I'm interested on this because I have both somfy blinds and Rfxtrx433e rfxcom module.

**Comment by bigkevmcd** [comment]
@alex198710 without tests, it won't get merged at all, if you have an interest in seeing it land, feel free to branch, rebase and add tests, otherwise it'll have to wait 'til I'm motivated enough to write tests for untested code.

**Comment by maxwellhadley** [comment]
@gizimoto There have been substantial changes to since this PR was raised and it now has merge conflicts. There are also changes to the format of packet type 0x01 in versions of the RFX firmware 1000 and above which may affect it. Any chance of reviewing your code and issuing a new PR against the current version?s (some tests would be nice, too)

**Comment by gizimoto** [comment]
@maxwellhadley I've left this a bit unfinished due to relocation - however I still have some Somfy stuff and will do my best to update the code base and submit another PR once able.

**Comment by maxwellhadley** [comment]
@gizimoto Any update on a new PR?

**Comment by cedbale** [comment]
i am also interested about this PR. Any update @gizimoto ?

**Comment by maxwellhadley** [comment]
OK I give in! Just ordered an RFXtrx433E so I can have a go implementing Somfy myself (I currently only have the older model that doesn't support it). I have found someone with a Somfy blind installed I can take a laptop round to for testing purposes.

**Comment by maxwellhadley** [comment]
The manual merge didn't quite work as expected, and GitHub hasn't noticed, but I think this PR has now been merged in OK - so I'm closing it. I'll work on the rfxcom:add-somfy-blinds branch.

**Comment by maxwellhadley** [comment]
@gizmoto I've got the code running and talking to my RFXtrx433E, but the RFX developer documentation for Somfy blinds is not exactly transparent. Presumably you have a working system, so could you please explain how the RFY devices are supposed to operate, e.g. how do I 'pair' a remote? And what does pairing a remote mean? How do I find out the ID and unit code of a blind to send it a command, including a 'program' command? What does the list remotes command do and why? Exactly where is this list stored - in the RFXtrx or in the blinds motor? Does this mean a blind motor can respond to multiple remotes? If there are multiple remotes in the list do I get one 'list' event with them all in, or one event per remote? If it's multiple events, how do I know when I've reached the last remote in the list? If the remote list is stored in the RFX, does it survive the firmware being re-flashed?
Thanks!

**Comment by gizimoto** [comment]
@maxwellhadley 
I assume you have the Somfy RTS programming documents - I believe I used the 'Adding or Deleting Transmistter' method.

Consider the RFX a remote, you need to pair RFX with a blind - the process is same as for real remotes, except that you send the program command to the RFX instead of pressing/holding the button as I recall.

You do not find the ID's for blinds, but you get the list of remotes and send commands for those remotes - the blinds must contain a list of remotes id's they listen and respond to.

List remotes command, simply returns the IDs paired in the RFX unit, I cannot recall the response format.

Unknown regarding a firmware flash.

Ill dig out my RFX, and a Somfy motor and answer better over the weekend.

**Comment by maxwellhadley** [comment]
@gizmoto I found the programming document, and it looks to me as if there are two different ways to associate a remote with a motor:
1. If the motor has never been paired (or it has been hard reset?) then it will pair with whatever sends a 'program' command to it first. In this case, Somfy recommend turning off everything else in range.
2. If the motor is already paired with a remote, press 'program' on the already-paired remote, wait for a response 'jog' and then press 'program' on the remote to be paired (presumably there is a timeout, don't know how long though). In this case, Somfy don't say anything about turning off other motors, though the RFXCOM manual says to do so

Turning off other motors isn't practical for me (it's a row of terraced houses where each house has a Somfy blind) so I hope it isn't vital!

I've done some experiments, and it's clear the remotes list is stored in the RFXtrx433E itself. You can add remotes and remove them without ever communicating with a Somfy motor. If there are multiple paired remotes, then in response to a 'listremotes' command the RFXtrx433E will send a response packet for each one, giving rise to a "list" event for each one. If there are no paired remotes, the RFXtrx433E does not respond at all. There is no 'end of list' marker.

I also find that the firmware (v1006) now includes support for ASA type blind motors using the Somfy/RFY packet type, and that these remotes are listed with a different response packet subtype (0x04 instead of 0x03) - when you list remotes, you get all remotes of both subtypes. This has meant I have had to make the subtype parameter to the Rfy constructor mandatory.

I have modified the code to generate a single "rfyremoteslist" event containing an array of remote 'params' objects, one for each remote (of both types) in the list. If there are no remotes stored, you get an empty array. This is achieved by using the already-existing timeout facility in the transmission queue. It should make it simpler for application code to handle, and the 10 second delay shouldn't cause too many problems. I propose deleting the per-remote "list" events - is this OK with you?

The 'params' structure is also changed slightly. I've added a remoteType property, with value either 'RFY' or 'ASA', to indicate the type of remote; and I discovered that the 'unknown' bytes are just whatever is left hanging around in the status message transmit buffer from the previous transmission (e.g. the "Copyright RFXCOM" banner) so I deleted the corresponding property.

I'll be adding ID element range-checking as per the RFXCOM SDK documentation, and I'll be changing the format of the deviceID parameter to match the transmitters for the other packet types. Oh and updating and extending the test coverage!

**Comment by maxwellhadley** [comment]
@gizmoto - Another thing. If I supply a numeric command to the Rfy.do() function, it always sends 'up', not the command number. That seems very weird! Is there a rational explanation?

**Comment by maxwellhadley** [comment]
OK! I just pushed a 'release candidate' commit to the add-somfy-blinds branch, if anyone is able to grab it & take it for a test drive I'd appreciate it.

**Pull request closed without merging**
